import { SampleProfile } from '../types';

export const SAMPLE_PROFILES: SampleProfile[] = [
  {
    id: 'sample_priya',
    name: 'Priya (25 yrs)',
    ageAndGender: '25 F • Student / Youth',
    riskLevel: 'low',
    badge: 'Low Risk Profile',
    tagline: 'Young age, physically active, no tobacco, normal vitals & BMI',
    answers: {
      hasEmergencySymptoms: false,
      ageGroup: 'under30',
      gender: 'female',
      activityLevel: 'active',
      smoking: 'never',
      alcohol: 'never',
      dietQuality: 'balanced',
      familyHistory: {
        diabetes: false,
        heartDisease: false,
        highBP: false,
        noneOrUnsure: true,
      },
      weightKg: 52,
      heightCm: 160,
      bmiSkipped: false,
      bloodPressure: 'normal',
      bloodSugar: 'normal',
    },
  },
  {
    id: 'sample_sunita',
    name: 'Sunita (34 yrs)',
    ageAndGender: '34 F • Homemaker & Weaver',
    riskLevel: 'moderate',
    badge: 'Moderate Risk Profile',
    tagline: 'Family sugar history, active daily walking, balanced home diet',
    answers: {
      hasEmergencySymptoms: false,
      ageGroup: '30to45',
      gender: 'female',
      activityLevel: 'active',
      smoking: 'never',
      alcohol: 'never',
      dietQuality: 'balanced',
      familyHistory: {
        diabetes: true,
        heartDisease: false,
        highBP: false,
        noneOrUnsure: false,
      },
      weightKg: 62,
      heightCm: 155,
      bmiSkipped: false,
      bloodPressure: 'normal',
      bloodSugar: 'normal',
    },
  },
  {
    id: 'sample_ramesh',
    name: 'Ramesh (48 yrs)',
    ageAndGender: '48 M • Shopkeeper',
    riskLevel: 'moderate',
    badge: 'Moderate-High Risk Profile',
    tagline: 'High BP history, occasional bidi, low physical activity',
    answers: {
      hasEmergencySymptoms: false,
      ageGroup: '46to60',
      gender: 'male',
      activityLevel: 'low',
      smoking: 'occasional',
      alcohol: 'never',
      dietQuality: 'high_salt',
      familyHistory: {
        diabetes: true,
        heartDisease: false,
        highBP: true,
        noneOrUnsure: false,
      },
      weightKg: 78,
      heightCm: 168,
      bmiSkipped: false,
      bloodPressure: 'high',
      bloodSugar: 'unknown',
    },
  },
  {
    id: 'sample_vikram',
    name: 'Vikram (63 yrs)',
    ageAndGender: '63 M • Retired Farmer',
    riskLevel: 'high',
    badge: 'High Risk Profile',
    tagline: 'Senior age, family heart history, elevated blood pressure & sugar',
    answers: {
      hasEmergencySymptoms: false,
      ageGroup: 'above60',
      gender: 'male',
      activityLevel: 'low',
      smoking: 'regular',
      alcohol: 'occasional',
      dietQuality: 'high_salt',
      familyHistory: {
        diabetes: true,
        heartDisease: true,
        highBP: true,
        noneOrUnsure: false,
      },
      weightKg: 84,
      heightCm: 170,
      bmiSkipped: false,
      bloodPressure: 'high',
      bloodSugar: 'high',
    },
  },
];
